<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="9" total="11" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="176945" started-at="2023-01-12T20:40:19 IST" finished-at="2023-01-12T20:43:16 IST">
    <groups>
      <group name="Regression">
        <method signature="InventaryPageTest.verifyURLTest()[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="verifyURLTest" class="TestCases.InventaryPageTest"/>
      </group> <!-- Regression -->
      <group name="smoke">
        <method signature="InventaryPageTest.verifyURLTest()[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="verifyURLTest" class="TestCases.InventaryPageTest"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="176945" started-at="2023-01-12T20:40:19 IST" finished-at="2023-01-12T20:43:16 IST">
      <class name="TestCases.InventaryPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="setup" is-config="true" duration-ms="101269" started-at="2023-01-12T20:40:20 IST" finished-at="2023-01-12T20:42:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyLinkedLogoTest()[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="verifyLinkedLogoTest" duration-ms="1041" started-at="2023-01-12T20:42:01 IST" finished-at="2023-01-12T20:42:02 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at TestCases.InventaryPageTest.verifyLinkedLogoTest(InventaryPageTest.java:113)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinkedLogoTest -->
        <test-method status="PASS" signature="closeBrowser(org.testng.ITestResult)[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="closeBrowser" is-config="true" duration-ms="14578" started-at="2023-01-12T20:42:02 IST" finished-at="2023-01-12T20:42:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLinkedLogoTest status=FAILURE method=InventaryPageTest.verifyLinkedLogoTest()[pri:0, instance:TestCases.InventaryPageTest@fad74ee] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="setup()[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="setup" is-config="true" duration-ms="46003" started-at="2023-01-12T20:42:17 IST" finished-at="2023-01-12T20:43:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyURLTest()[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="verifyURLTest" duration-ms="136" started-at="2023-01-12T20:43:03 IST" finished-at="2023-01-12T20:43:03 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [https://www.saucedemo.com/inventory.html]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [https://www.saucedemo.com/inventory.html]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestCases.InventaryPageTest.verifyURLTest(InventaryPageTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyURLTest -->
        <test-method status="PASS" signature="closeBrowser(org.testng.ITestResult)[pri:0, instance:TestCases.InventaryPageTest@fad74ee]" name="closeBrowser" is-config="true" duration-ms="13133" started-at="2023-01-12T20:43:03 IST" finished-at="2023-01-12T20:43:16 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyURLTest status=FAILURE method=InventaryPageTest.verifyURLTest()[pri:0, instance:TestCases.InventaryPageTest@fad74ee] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- TestCases.InventaryPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
